/**
 * Shared school stamp — drawn on every PDF document generated by the app
 * (receipts, payslips, bordereaux, reports) in their "cachet" zone.
 *
 * The stamp PNG lives in `public/tampon.png` and is loaded at runtime via
 * fetch → decoded + downscaled on a canvas. The source file is a 1254px
 * distressed-texture PNG (~1.4 MB); embedding it at full size would balloon
 * every generated PDF (≈5 MB), so it is downscaled to ≤ 420px here — far more
 * than enough for the ~20 mm stamp box, at a fraction of the payload.
 *
 * Strictly non-blocking: if the image cannot be loaded or decoded (offline,
 * tests, missing file), the document is still generated — only the stamp is
 * skipped. The data URL is cached after the first successful load.
 */

/** StampableDoc — the slice of jsPDF used here (kept narrow on purpose). */
interface StampableDoc {
  addImage: (
    imageData: string | HTMLImageElement | HTMLCanvasElement,
    format: string,
    x: number,
    y: number,
    w: number,
    h: number,
  ) => void;
}

const STAMP_MAX_EDGE = 420;

let stampDataUrlPromise: Promise<string | null> | null = null;

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    if (typeof FileReader === 'undefined') {
      reject(new Error('FileReader unavailable'));
      return;
    }
    const reader = new FileReader();
    reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : '');
    reader.onerror = () => reject(new Error('FileReader error'));
    reader.readAsDataURL(blob);
  });
}

/**
 * Decodes a stamp blob and downscales it to STAMP_MAX_EDGE via canvas.
 * Falls back to the raw data URL when canvas decoding is unavailable.
 */
async function downscaleStampBlob(blob: Blob): Promise<string> {
  const rawDataUrl = await blobToDataUrl(blob);
  if (typeof Image === 'undefined' || typeof document === 'undefined') return rawDataUrl;
  try {
    const objectUrl = URL.createObjectURL(blob);
    try {
      const img = new Image();
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error('image decode failed'));
        img.src = objectUrl;
      });
      const scale = Math.min(1, STAMP_MAX_EDGE / Math.max(img.width, img.height));
      const w = Math.max(1, Math.round(img.width * scale));
      const h = Math.max(1, Math.round(img.height * scale));
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('no 2d context');
      ctx.drawImage(img, 0, 0, w, h);
      return canvas.toDataURL('image/png');
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  } catch {
    return rawDataUrl;
  }
}

/** Data URL of the stamp (cached), or null when unavailable. */
function getStampDataUrl(): Promise<string | null> {
  if (!stampDataUrlPromise) {
    stampDataUrlPromise = (async (): Promise<string | null> => {
      try {
        // Relative to the page origin — works in dev, preview and production.
        const res = await fetch('tampon.png');
        if (!res.ok) return null;
        const blob = await res.blob();
        const dataUrl = await downscaleStampBlob(blob);
        return dataUrl || null;
      } catch {
        return null;
      }
    })();
  }
  return stampDataUrlPromise;
}

/**
 * Draws the school stamp centered on (cx, cy) with the given diameter (mm).
 * No-op when the image is unavailable — the document still generates.
 */
export async function drawSchoolStamp(
  doc: StampableDoc,
  cx: number,
  cy: number,
  diameterMm: number,
): Promise<void> {
  try {
    const dataUrl = await getStampDataUrl();
    if (!dataUrl) return;
    doc.addImage(dataUrl, 'PNG', cx - diameterMm / 2, cy - diameterMm / 2, diameterMm, diameterMm);
  } catch {
    /* never break the document because of the stamp */
  }
}
