/**
 * Shared school stamp — drawn on every PDF document generated by the app
 * (receipts, payslips, bordereaux, reports) in their "cachet" zone.
 *
 * The stamp PNG lives in `public/tampon.png` and is loaded at runtime via
 * fetch. The COMMITTED asset is already optimised: 300 px, palette-indexed,
 * flattened on pure white (~38 KB). The original stamp was a 1254 px
 * distressed-texture PNG of ~1.4 MB — embedding it at full size ballooned
 * every generated PDF to ≈5 MB; the optimised 300 px file keeps ~380 dpi in
 * the 20 mm stamp box (≈320 dpi in the widest 24 mm box) while the PDF
 * payload drops to ~90 KB. Regenerate it from any larger capture with
 * `node scripts/optimize-stamp.mjs` — a pure-Node PNG pipeline, no external
 * image dependency.
 *
 * A canvas guard (STAMP_MAX_EDGE) remains for robustness: if the file in
 * `public/` is ever replaced by a larger one, it is decoded and downscaled
 * here so documents never regress in size. When the fetched image is already
 * within the cap, its raw data URL is used as-is (no lossy second encode).
 *
 * Strictly non-blocking: if the image cannot be loaded or decoded (offline,
 * tests, missing file), the document is still generated — only the stamp is
 * skipped. The data URL is cached after the first successful load.
 */

/** StampableDoc — the slice of jsPDF used here (kept narrow on purpose). */
interface StampableDoc {
  addImage: (
    imageData: string | HTMLImageElement | HTMLCanvasElement,
    format: string,
    x: number,
    y: number,
    w: number,
    h: number,
  ) => void;
}

const STAMP_MAX_EDGE = 300;

let stampDataUrlPromise: Promise<string | null> | null = null;

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    if (typeof FileReader === 'undefined') {
      reject(new Error('FileReader unavailable'));
      return;
    }
    const reader = new FileReader();
    reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : '');
    reader.onerror = () => reject(new Error('FileReader error'));
    reader.readAsDataURL(blob);
  });
}

/**
 * Decodes a stamp blob and downscales it to STAMP_MAX_EDGE via canvas.
 * Falls back to the raw data URL when canvas decoding is unavailable.
 */
async function downscaleStampBlob(blob: Blob): Promise<string> {
  const rawDataUrl = await blobToDataUrl(blob);
  if (typeof Image === 'undefined' || typeof document === 'undefined') return rawDataUrl;
  try {
    const objectUrl = URL.createObjectURL(blob);
    try {
      const img = new Image();
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error('image decode failed'));
        img.src = objectUrl;
      });
      const srcW = img.naturalWidth || img.width;
      const srcH = img.naturalHeight || img.height;
      const scale = Math.min(1, STAMP_MAX_EDGE / Math.max(srcW, srcH));
      // Already within the cap — use the fetched file untouched (no second
      // encode, no quality loss).
      if (scale === 1) return rawDataUrl;
      const w = Math.max(1, Math.round(srcW * scale));
      const h = Math.max(1, Math.round(srcH * scale));
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('no 2d context');
      ctx.drawImage(img, 0, 0, w, h);
      return canvas.toDataURL('image/png');
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  } catch {
    return rawDataUrl;
  }
}

/** Data URL of the stamp (cached), or null when unavailable. */
function getStampDataUrl(): Promise<string | null> {
  if (!stampDataUrlPromise) {
    stampDataUrlPromise = (async (): Promise<string | null> => {
      try {
        // Relative to the page origin — works in dev, preview and production.
        const res = await fetch('tampon.png');
        if (!res.ok) return null;
        const blob = await res.blob();
        const dataUrl = await downscaleStampBlob(blob);
        return dataUrl || null;
      } catch {
        return null;
      }
    })();
  }
  return stampDataUrlPromise;
}

/**
 * Draws the school stamp centered on (cx, cy) with the given diameter (mm).
 * No-op when the image is unavailable — the document still generates.
 */
export async function drawSchoolStamp(
  doc: StampableDoc,
  cx: number,
  cy: number,
  diameterMm: number,
): Promise<void> {
  try {
    const dataUrl = await getStampDataUrl();
    if (!dataUrl) return;
    doc.addImage(dataUrl, 'PNG', cx - diameterMm / 2, cy - diameterMm / 2, diameterMm, diameterMm);
  } catch {
    /* never break the document because of the stamp */
  }
}
