/**
 * Shared school stamp — drawn on every PDF document generated by the app
 * (receipts, payslips, bordereaux, reports) in their "cachet" zone.
 *
 * The stamp PNG lives in `public/tampon.png` and is loaded at runtime via
 * fetch. The COMMITTED asset is already optimised: 300 px, transparent
 * background (~34 KB) — the original white matte was un-composited to alpha
 * (a = 255 − min(r,g,b), c' = (c − (255−a))·255/a) so the seal can sit ON
 * printed lines (signature underlines, table rules): only the ink strokes
 * cover the paper, the line shows through around them. The original stamp
 * was a 1254 px distressed-texture PNG of ~1.4 MB — embedding it at full size
 * ballooned every generated PDF to ≈5 MB; the optimised 300 px file keeps
 * ~380 dpi in the 20 mm stamp box (≈320 dpi in the widest 24 mm box) while
 * the PDF payload drops to ~90 KB. Regenerate it from any larger capture with
 * `node scripts/optimize-stamp.mjs` — a pure-Node PNG pipeline, no external
 * image dependency — then re-apply the white→alpha un-matte above (that
 * script composites on white; the transparent background is what lets a
 * stamp overlap printed lines cleanly).
 *
 * A canvas guard (STAMP_MAX_EDGE) remains for robustness: if the file in
 * `public/` is ever replaced by a larger one, it is decoded and downscaled
 * here so documents never regress in size. When the fetched image is already
 * within the cap, its raw data URL is used as-is (no lossy second encode).
 *
 * Strictly non-blocking: if the image cannot be loaded or decoded (offline,
 * tests, missing file), the document is still generated — only the stamp is
 * skipped. The data URL is cached after the first successful load.
 */

/** StampableDoc — the slice of jsPDF used here (kept narrow on purpose). */
interface StampableDoc {
  addImage: (
    imageData: string | HTMLImageElement | HTMLCanvasElement,
    format: string,
    x: number,
    y: number,
    w: number,
    h: number,
  ) => void;
}

/**
 * StampablePdfLibDoc — pdf-lib variant used by the template-overlay
 * generators (fiche/bulletin): the stamp PNG is embedded via the document's
 * embedPng and drawn on the template page with the same mm coordinates
 * (mmToPdfX/mmToPdfY anchored to the top of the page, like the fiche).
 */
interface StampablePdfLibDoc {
  embedPng: (png: string | Uint8Array | ArrayBuffer) => Promise<unknown>;
  page: import('pdf-lib').PDFPage;
  mmToPdfX: (mm: number) => number;
  mmToPdfY: (mm: number) => number;
}

const STAMP_MAX_EDGE = 300;

/** 1 mm in PDF points (72/25.4). */
const PT_PER_MM = 72 / 25.4;

let stampDataUrlPromise: Promise<string | null> | null = null;

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    if (typeof FileReader === 'undefined') {
      reject(new Error('FileReader unavailable'));
      return;
    }
    const reader = new FileReader();
    reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : '');
    reader.onerror = () => reject(new Error('FileReader error'));
    reader.readAsDataURL(blob);
  });
}

/**
 * Decodes a stamp blob and downscales it to STAMP_MAX_EDGE via canvas.
 * Falls back to the raw data URL when canvas decoding is unavailable.
 */
async function downscaleStampBlob(blob: Blob): Promise<string> {
  const rawDataUrl = await blobToDataUrl(blob);
  if (typeof Image === 'undefined' || typeof document === 'undefined') return rawDataUrl;
  try {
    const objectUrl = URL.createObjectURL(blob);
    try {
      const img = new Image();
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error('image decode failed'));
        img.src = objectUrl;
      });
      const srcW = img.naturalWidth || img.width;
      const srcH = img.naturalHeight || img.height;
      const scale = Math.min(1, STAMP_MAX_EDGE / Math.max(srcW, srcH));
      // Already within the cap — use the fetched file untouched (no second
      // encode, no quality loss).
      if (scale === 1) return rawDataUrl;
      const w = Math.max(1, Math.round(srcW * scale));
      const h = Math.max(1, Math.round(srcH * scale));
      const canvas = document.createElement('canvas');
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('no 2d context');
      ctx.drawImage(img, 0, 0, w, h);
      return canvas.toDataURL('image/png');
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  } catch {
    return rawDataUrl;
  }
}

/** Data URL of the stamp (cached), or null when unavailable. */
function getStampDataUrl(): Promise<string | null> {
  if (!stampDataUrlPromise) {
    stampDataUrlPromise = (async (): Promise<string | null> => {
      try {
        // Relative to the page origin — works in dev, preview and production.
        const res = await fetch('tampon.png');
        if (!res.ok) return null;
        const blob = await res.blob();
        const dataUrl = await downscaleStampBlob(blob);
        return dataUrl || null;
      } catch {
        return null;
      }
    })();
  }
  return stampDataUrlPromise;
}

/**
 * Draws the school stamp centered on (cx, cy) with the given diameter (mm).
 * No-op when the image is unavailable — the document still generates.
 *
 * Accepts BOTH document kinds: the classic jsPDF slice (addImage) used by the
 * drawn generators, and the pdf-lib slice (embedPng + page) used by the
 * template-overlay generators (fiche individuelle, bulletin de paie).
 */
export async function drawSchoolStamp(
  doc: StampableDoc | StampablePdfLibDoc,
  cx: number,
  cy: number,
  diameterMm: number,
): Promise<void> {
  try {
    const dataUrl = await getStampDataUrl();
    if (!dataUrl) return;
    if ('addImage' in doc) {
      doc.addImage(dataUrl, 'PNG', cx - diameterMm / 2, cy - diameterMm / 2, diameterMm, diameterMm);
      return;
    }
    // pdf-lib template overlay: embed the PNG and draw it on the template page.
    const image = (await doc.embedPng(dataUrl)) as Parameters<import('pdf-lib').PDFPage['drawImage']>[0];
    const sizePt = diameterMm * PT_PER_MM;
    doc.page.drawImage(image, {
      x: doc.mmToPdfX(cx - diameterMm / 2),
      y: doc.mmToPdfY(cy + diameterMm / 2),
      width: sizePt,
      height: sizePt,
    });
  } catch {
    /* never break the document because of the stamp */
  }
}
